#! /usr/bin/perl
#
# (C)2006 Luca Corti, Lorenzo Vigano' - (C) 2007 Luca Corti
# $Id: check_kannel.pl,v 1.1.1 2007/09/03 15:36:23 lcorti Exp $
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA

require 5.004;
use strict;
use POSIX;
use LWP::UserAgent;
use XML::DOM;
use XML::XPath;
use XML::XPath::XMLParser;
use Getopt::Long;
use vars qw($opt_V $opt_v $opt_P $opt_p $opt_h $opt_H $opt_s $opt_t $opt_w $opt_c $opt_i $opt_j $opt_k $opt_o $opt_q $opt_r $opt_l $opt_m $opt_S $opt_W $opt_b $opt_B $opt_F $opt_T $smsboxwarn $smsboxwarnstatus $smsboxcritstatus $smsboxq @smscqwarn @smscqcrit $finaloutput $smsconlinecrit $smsconlinewarn $smscqcrit $smscqwarn $critstatus $warnstatus @downsmsc $storesizestatus %kannel %plugin $response $ua $xp $PROGNAME $PROGREV);
use lib "/usr/lib/nagios/plugins";
use utils qw($TIMEOUT %ERRORS &print_revision);

$PROGNAME="check_kannel";
$PROGREV='$Revision: 1.1.1 $';

$ENV{'PATH'}='';
$ENV{'BASH_ENV'}='';
$ENV{'ENV'}='';

sub print_output($);
sub print_help();
sub print_usage();

# Plugin data
%plugin = (
	hostname    => 'localhost',
	password    => '',
	port        => '13000',
	timeout     => "$TIMEOUT",
	url         => '',
	verbose     => '0',
	check       => {
		smsbox => 0,
		wapbox => 0
	},
	thresholds  => {
		sms => {
			received => {
				total => {
					warning  => 0,
					critical => 0
				},
				queued => {
					warning  => 0,
					critical => 0
				}
			},
			sent => {
				total => {
					warning  => 0,
					critical => 0
				},
				queued => {
					warning  => 0,
					critical => 0
				}
			},
			storesize => 0
		},
		dlr => {
			queued => {
				warning  => 0,
				critical => 0
			}
		},
		boxes => {
			smsbox => {
				online => {
					warning  => 1,
					critical => 0
				},
				queued => ''
			},
			wapbox => {
				online => {
					warning  => 1,
					critical => 0
				}
			}
		},
		smscs => {
			online => {
				warning  => 1,
				critical => 0
			},
			queued => {
				warning  => 0,
				critical => 0
			}
		}
	}
);

# Kannel status.xml imported data structure
%kannel = (
	version => '',
	status  => '',
	wdp => {
		received => {
			total  => 0,
			queued => 0
		},
		sent => {
			total  => 0,
			queued => 0
		},
	},
	sms => {
		received => {
			total  => 0,
			queued => 0
		},
		sent => {
			total  => 0,
			queued => 0
		},
		storesize => '',
		inbound   => '',
		outbound  => ''
	},
	dlr  => {
		queued  => '',
		storage => ''
	},
	boxes => {
		smsbox => {
			count  => 0,
			online => 0
		},
		wapbox => {
			count  => 0,
			online => 0
		}
	},
	smscs => {
		count  => '',
		online => 0,
		smsc => {
		     status => '',
		     "admin-id" => '',
		     failed => '',
		     queued => '',
		     sms => {
			 inbound => '',
			 outbound => ''
		    }
		}
	}
);

Getopt::Long::Configure('bundling');
GetOptions
	("V"   => \$opt_V, "version"           => \$opt_V,
	 "h"   => \$opt_h, "help"              => \$opt_h,
	 "v"   => \$opt_v, "verbose"           => \$opt_v,
	 "s"   => \$opt_s, "secure"            => \$opt_s,
	 "S"   => \$opt_S, "smsbox"            => \$opt_S,
	 "W"   => \$opt_W, "wapbox"            => \$opt_W,
	 "w=i" => \$opt_w, "warning=i"         => \$opt_w,
	 "c=i" => \$opt_c, "critical=i"        => \$opt_c,
	 "i=i" => \$opt_i, "smsrecvqwarn=i"    => \$opt_i,
	 "j=i" => \$opt_j, "smsrecvqcrit=i"    => \$opt_j,
	 "k=i" => \$opt_k, "smsrecvrate=i"     => \$opt_k,
	 "o=i" => \$opt_o, "smssendqwarn=i"    => \$opt_o,
	 "q=i" => \$opt_q, "smssendqcrit=i"    => \$opt_q,
	 "r=i" => \$opt_r, "smssendrate=i"     => \$opt_r,
	 "l=i" => \$opt_l, "smscqueuedwarn=i"  => \$opt_l,
	 "m=i" => \$opt_m, "smscqueuedcrit=i"  => \$opt_m,
	 "t=i" => \$opt_t, "timeout=i"         => \$opt_t,
	 "H=s" => \$opt_H, "host=s"            => \$opt_H,
	 "P=i" => \$opt_P, "port=i"            => \$opt_P,
	 "b=i" => \$opt_b, "smsboxwarn=i"      => \$opt_b, #set by mfouad to set smsbox count that should be connected
	 "B=i" => \$opt_B, "smsboxcrit=i"      => \$opt_B, #set by mfouad to set smsbox count that should be connected
	 "F=i" => \$opt_F, "smsboxq=i"         => \$opt_F, #set by mfouad to set smsbox queue
	 "T=i" => \$opt_T, "storesize=i"       => \$opt_T, #set by mfouad to set smsbox queue
	 "p=s" => \$opt_p, "password=s"        => \$opt_p);

if ($opt_V)
{
	print_revision($PROGNAME,$PROGREV);
	exit $ERRORS{'UNKNOWN'};
}

if ($opt_h)
{
	print_help();
	exit $ERRORS{'UNKNOWN'};
}

if ($opt_v)
{
	$plugin{verbose} = 1;
}

if ($opt_H and $opt_H =~ m/^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+|[a-zA-Z][-a-zA-Z0-9]+(\.[a-zA-Z][-a-zA-Z0-9]+)*)$/)
{
	$plugin{hostname} = $opt_H;
}

if ($opt_P and $opt_P =~ /^([0-9]+)$/)
{
	$plugin{port} = $1;
}

if ($opt_p)
{
	$plugin{password} = $opt_p;
}

if ($opt_t and $opt_t =~ /^([0-9]+)$/)
{
	$plugin{timeout} = $1;
}

if ($opt_S)
{
	$plugin{check}{smsbox} = 1;
}

if ($opt_W)
{
	$plugin{check}{wapbox} = 1;
}

if ($opt_w and $opt_w =~ /^([0-9]+)$/)
{
	$plugin{thresholds}{smscs}{online}{warning} = $1;
}

if ($opt_c and $opt_c =~ /^([0-9]+)$/)
{
	$plugin{thresholds}{smscs}{online}{critical} = $1;
}

if ($opt_i and $opt_i =~ /^([0-9]+)$/)
{
	$plugin{thresholds}{sms}{received}{queued}{warning} = $1;
}

if ($opt_j and $opt_j =~ /^([0-9]+)$/)
{
	$plugin{thresholds}{sms}{received}{queued}{critical} = $1;
}

if ($opt_o and $opt_o =~ /^([0-9]+)$/)
{
	$plugin{thresholds}{sms}{sent}{queued}{warning} = $1;
}

if ($opt_q and $opt_q =~ /^([0-9]+)$/)
{
	$plugin{thresholds}{sms}{sent}{queued}{critical} = $1;
}

if ($opt_l and $opt_l =~ /^([0-9]+)$/)
{
	$plugin{thresholds}{smscs}{queued}{warning} = $1;
}

if ($opt_m and $opt_m =~ /^([0-9]+)$/)
{
	$plugin{thresholds}{smscs}{queued}{critical} = $1;
}

if ($opt_b =~ /^([0-9]+)$/)
{
	$plugin{thresholds}{boxes}{smsbox}{online}{warning} = $1;
}
if ($opt_B =~ /^([0-9]+)$/)
{
	$plugin{thresholds}{boxes}{smsbox}{online}{critical} = $1;
}
if ($opt_F =~ /^([0-9]+)$/)
{
	$plugin{thresholds}{boxes}{smsbox}{queued} = $1;
}
if ($opt_T =~ /^([0-9]+)$/)
{
	$plugin{thresholds}{sms}{storesize} = $1;
}
if ($plugin{thresholds}{smscs}{online}{critical} > $plugin{thresholds}{smscs}{online}{warning})
{
	print "Fatal: Online SMSCs critical offset ($plugin{thresholds}{smscs}{online}{critical}) must be smaller than warning offset ($plugin{thresholds}{smscs}{online}{warning}).\n";
	print_usage();
	exit $ERRORS{"UNKNOWN"};
}

#if ($plugin{thresholds}{sms}{received}{queued}{warning} >= $plugin{thresholds}{sms}{received}{queued}{critical})
#{
#	print "Fatal: SMS received queues critical offset must be smaller than warning offset.\n";
#	print_usage();
#	exit $ERRORS{"UNKNOWN"};
#}

#if ($plugin{thresholds}{sms}{sent}{queued}{warning} >= $plugin{thresholds}{sms}{sent}{queued}{critical})
#{
#	print "Fatal: SMS sent queues critical offset must be smaller than warning offset.\n";
#	print_usage();
#	exit $ERRORS{"UNKNOWN"};
#}

# Just in case of problems, let's not hang Nagios
$SIG{'ALRM'} = sub
{
	print ("UNKNOWN: No response from Kannel server (timeout)\n");
	exit $ERRORS{"UNKNOWN"};
};

alarm($plugin{timeout});

$plugin{url}="http://".$plugin{hostname}.":".$plugin{port}."/status.xml?password=".$plugin{password};
$plugin{verbose} and print"Will try to get status from ".$plugin{url}."...";

# Get status.xml from server
$ua = LWP::UserAgent->new;
if ($opt_s)
{
	$ua->protocols_allowed([ 'https' ]);
}
else
{
	$ua->protocols_allowed([ 'http' ]);
}
$ua->timeout(10);
$ua->env_proxy;

$response = $ua->get($plugin{url});

if ($response->is_success)
{
	$plugin{verbose} and print " got response from server!\n" and print "\n".$response->content."\n";
}
else
{
	print "CRITICAL: Can't connect to Kannel: ".$response->status_line."\n";
	exit $ERRORS{"CRITICAL"};
}

$xp = XML::XPath->new(xml => $response->content);

if ($xp->getNodeText("/gateway") =~ /Denied/)
{
	print "UNKNOWN: Can't connect to Kannel: Access Denied (wrong password?)\n";
	exit $ERRORS{"UNKNOWN"};
}

$kannel{status} = $xp->getNodeText("/gateway/status");
($kannel{status}, $kannel{uptime}) = split(/,/,$kannel{status});
$kannel{sms}{received}{queued} = $xp->getNodeText("/gateway/sms/received/queued");
$kannel{sms}{sent}{queued} = $xp->getNodeText("/gateway/sms/sent/queued");
$kannel{sms}{inbound} = $xp->getNodeText("/gateway/sms/inbound");
$kannel{sms}{outbound} = $xp->getNodeText("/gateway/sms/outbound");
$kannel{sms}{storesize} = $xp->getNodeText("/gateway/sms/storesize");
$kannel{dlr}{queued} = $xp->getNodeText("/gateway/dlr/queued");
$kannel{dlr}{storage} = $xp->getNodeText("/gateway/dlr/storage");
$kannel{smscs}{count} = $xp->getNodeText("/gateway/smscs/count");
#$kannel{smscs}{smsc}{sms}{inbound} = $xp->getNodeText("/gateway/smscs/smsc/sms/inbound");
#$kannel{smscs}{smsc}{sms}{outbound} = $xp->getNodeText("/gateway/smscs/smsc/sms/outbound");

# Get number of total/online sms/wap boxes
foreach my $box ($xp->findnodes("/gateway/boxes/box"))
{

	my $type = $box->findnodes("type");
	my $status = $box->findnodes("status");

	# smsboxes
	if ($type->string_value eq "smsbox")
	{
		$kannel{boxes}{smsbox}{count}++;

		if ($status->string_value =~ /^on-line/)
		{
			$kannel{boxes}{smsbox}{online}++;
		}
	}
	# wapboxes
	elsif ($type->string_value eq "wapbox")
	{
		$kannel{boxes}{wapbox}{count}++;
		if ($status->string_value =~ /^on-line/)
		{
			$kannel{boxes}{wapbox}{online}++;
		}
	}

}

# Get number of total/online/queued smscs
foreach my $smsc ($xp->findnodes("/gateway/smscs/smsc"))
{
    my $status = $smsc->findnodes("status");
    my $queued = $smsc->findnodes("queued");
    my $id = $smsc->findnodes("admin-id")->string_value;
    my $inbound =  $smsc->findnodes("sms/inbound")->string_value;
    my $outbound =  $smsc->findnodes("sms/outbound")->string_value;
    # onlines
	if ($status->string_value =~ /^online/)
	{
		$kannel{smscs}{online}++;
	}
	else {
		push (@downsmsc, $id);
}

    # catching queued values
    $kannel{smscs}{$id}{queued} = $queued->string_value;
    #catching throughput in & out
    $kannel{smscs}{$id}{sms}{inbound} = $inbound;
    $kannel{smscs}{$id}{sms}{outbound} = $outbound;
}
##check for store storage size

if ( $plugin{thresholds}{sms}{storesize} > 0 and $plugin{thresholds}{sms}{storesize}  < $kannel{sms}{storesize} )
{
	$storesizestatus = "Storesize Warning! store:$kannel{sms}{storesize}/$plugin{thresholds}{sms}{storesize} configured"
}


# Kannel running
if ($kannel{status} eq 'running')
{

	# smsboxes connected only used critical so removed the "=" from below equation  $kannel{boxes}{smsbox}{online} <= $plugin{thresholds}{boxes}{smsbox}{online}{critical}
	if ($plugin{check}{smsbox} and $kannel{boxes}{smsbox}{online} >= 0 and $kannel{boxes}{smsbox}{online} < $plugin{thresholds}{boxes}{smsbox}{online}{critical})
	{
		$smsboxcritstatus = "SMSBox Critial threshold! Online Boxes is $kannel{boxes}{smsbox}{online}/$plugin{thresholds}{boxes}{smsbox}{online}{critical} configured";
#		exit print_output('CRITICAL');

	}
	elsif ($kannel{boxes}{smsbox}{online} >= $plugin{thresholds}{boxes}{smsbox}{online}{critical} and $kannel{boxes}{smsbox}{online} <= $plugin{thresholds}{boxes}{smsbox}{online}{warning} and $kannel{boxes}{smsbox}{online} > 1)
	{ ## NOT USED FOR US RIGHT NOW
		$smsboxwarnstatus = "SMSBox Warning threshold! Online Boxes is  $kannel{boxes}{smsbox}{online}/$plugin{thresholds}{boxes}{smsbox}{online}{warning} configured";
#		exit print_output('WARNING');
	}

	# wapboxes running
	if ($plugin{check}{wapbox} and $kannel{boxes}{wapbox}{online} >= 0 and $kannel{boxes}{wapbox}{online} <= $plugin{thresholds}{boxes}{wapbox}{online}{critical})
	{
#		$critstatus = 1;
#		exit print_output('CRITICAL');

	}
	elsif ($kannel{boxes}{wapbox}{online} >= $plugin{thresholds}{boxes}{wapbox}{online}{critical} and $kannel{boxes}{wapbox}{online} <= $plugin{thresholds}{boxes}{wapbox}{online}{warning} and $kannel{boxes}{wapbox}{online} > 1)
	{
#		$warnstatus = 1;
#		exit print_output('WARNING');

	}

	# smscs online
	if ($kannel{smscs}{online} >= 0 and $kannel{smscs}{online} <= $plugin{thresholds}{smscs}{online}{critical})
	{
		$smsconlinecrit = "SMSC Critial threshold! Online SMSCc is $kannel{smscs}{online}/$plugin{thresholds}{smscs}{online}{critical} configured";
#		$critstatus = 1;
#		exit print_output('CRITICAL');
	}
	elsif ($kannel{smscs}{online} >= $plugin{thresholds}{smscs}{online}{critical} and $kannel{smscs}{online} <= $plugin{thresholds}{smscs}{online}{warning} and $kannel{smscs}{online} > 1)
	{
		$smsconlinewarn = "SMSC Warning threshold! Online SMSCc is $kannel{smscs}{online}/$plugin{thresholds}{smscs}{online}{warning} configured";
#		$warnstatus = 1;
#		exit print_output('WARNING');
	}
	# smscs queued
    foreach my $id (keys %{$kannel{smscs}})
    {
        next if ($id eq 'online' || $id eq 'count');
        if ($kannel{smscs}{$id}{queued} >= $plugin{thresholds}{smscs}{queued}{critical})
	    {
		push (@smscqcrit, "$id: $kannel{smscs}{$id}{queued} / Inbound: $kannel{smscs}{$id}{sms}{inbound} / Outbound:$kannel{smscs}{$id}{sms}{outbound}");
#		$smscqcrit = "Queue/SMSC Critical!";
#	    	exit print_output('CRITICAL');

	    }
	    elsif ($kannel{smscs}{$id}{queued} < $plugin{thresholds}{smscs}{queued}{critical} and $kannel{smscs}{$id}{queued} >= $plugin{thresholds}{smscs}{queued}{warning})
	    {
		push (@smscqwarn, "$id: $kannel{smscs}{$id}{queued} / Inbound: $kannel{smscs}{$id}{sms}{inbound} / Outbound:$kannel{smscs}{$id}{sms}{outbound}");
#		$smscqwarn = "Queue/SMSC Warning!";
#	    	exit print_output('WARNING');
	    }
    }

	if ($plugin{thresholds}{sms}{received}{queued}{warning} != 0 and $plugin{thresholds}{sms}{received}{queued}{critical} != 0)
	{
		if ($kannel{sms}{received}{queued} > $plugin{thresholds}{sms}{received}{queued}{critical} or $kannel{sms}{sent}{queued} > $plugin{thresholds}{sms}{sent}{queued}{critical})
		{
			$critstatus = 1;
#			exit print_output('CRITICAL');
		}
	}

	if ($plugin{thresholds}{sms}{sent}{queued}{warning} != 0 and $plugin{thresholds}{sms}{sent}{queued}{critical} != 0)
	{

		if ($kannel{sms}{received}{queued} > $plugin{thresholds}{sms}{received}{queued}{warning} or $kannel{sms}{sent}{queued} > $plugin{thresholds}{sms}{sent}{queued}{warning})
		{
			$warnstatus = 1;
#			exit print_output('WARNING');
		}

	}
	else
	{
		$finaloutput = 'OK';
#		exit print_output('OK');
	}

}
elsif ($kannel{status} =~ /^(suspended|isolated|full|shutdown)/)
{
	$warnstatus = 1;
#	exit print_output('WARNING');
}
else
{
	$warnstatus = 1;
#	exit print_output('CRITICAL');
}

#### subs

if ($smsboxwarnstatus || $smsconlinewarn || @smscqwarn || $storesizestatus ){
exit print_output('WARNING');
}
elsif ( $smsboxcritstatus || $smsconlinecrit || @smscqcrit ){
exit print_output('CRITICAL');
}
else {exit print_output('OK');}

sub print_output($)
{
	my $state = shift;
	print "Kannel $state - $kannel{status},$kannel{uptime}, $kannel{boxes}{smsbox}{online}/$kannel{boxes}{smsbox}{count} SMSBOX, $kannel{boxes}{wapbox}{online}/$kannel{boxes}{wapbox}{count} WAPBOX, $kannel{smscs}{online}/$kannel{smscs}{count} SMSC, $kannel{sms}{received}{queued}/$kannel{sms}{sent}{queued} SMS queued in/out, $kannel{dlr}{queued} DLR queued ($kannel{dlr}{storage}), store-file $kannel{sms}{storesize} bytes \n\n";


if ($smsboxcritstatus) {
	print "$smsboxcritstatus\n";
}
elsif ($smsboxwarnstatus){ ##NOT USED, shouldn't be viewed
	print "$smsboxwarnstatus\n"
}

if ($smsconlinecrit) {
print "$smsconlinecrit\n";
}
if ($smsconlinewarn) {
print "$smsconlinewarn\n";
}
if (@downsmsc) {
print "Down SMSCs:\n";
print join("\n",@downsmsc),"\n";
}
if (@smscqwarn){
print "\nQueue/SMSC Warning!.. SMSCs:\n";
print join("\n",@smscqwarn),"\n";
}
if (@smscqcrit){
print "\nQueue/SMSC Critical!.. SMSCs:\n";
print join("\n",@smscqcrit),"\n";
}

if ($storesizestatus){
print "$storesizestatus\n"
}

#print "SMSC queues: \n";
#    foreach my $id (keys %{$kannel{smscs}})
#    {
#        next if ($id eq 'online' || $id eq 'count');
#        print " $id: $kannel{smscs}{$id}{queued}";
#    }
    print "\n";
	return $ERRORS{"$state"};
}

sub print_usage()
{
	print "Usage: $PROGNAME [ OPTIONS ]\n";
}

sub print_help()
{
	print_revision($PROGNAME, $PROGREV);
	print "Copyright (c) 2006 Luca Corti, Lorenzo Vigano - 2007 Luca Corti\n";
	print "\n";
	print "Checks the status of the process, online sms and wap boxes, connected SMSCs, SMS queues and delivery rate for a kannel instance via the status.xml interface.";
	print "\n";
	print_usage();
	print "Checks the Kannel, configured SMSCs and SMS received/sent queues/rates on <host> via the status.xml interface.

-w (--warning)
     Number of connected SMSCs below which a warning status will be generated.
     Defaults to 1.
-c (--critical)
     Number of connected SMSCs below which a critical status will be generated.
     Defaults to 0.
-b (--smsboxwarn)
     Number of smsboxes that should be connected, if online boxes below, a Warning status will be generated.
-B (--smsboxcrit)
     Number of smsboxes that should be connected, if online boxes below, a Critical status will be generated.
-F (--smsboxq)
     Number of queue at smsboxes greater, a Critical status will be generated.
-S (--smsbox)
     Consider absence of at least a SMSBOX process a critical condition.. make use of smsboxwarn.
     Defaults to false.
-W (--wapbox)
     Consider absence of at least a WAPBOX process a critical condition.
     Defaults to false.
-i (--smsrecvqwarn)
     Number of SMSs in the receive queue above which a warning status will be generated.
     Defaults to 0.
-j (--smsrecvqcrit)
     Number of SMSs in the receive queue above which a critical status will be generated.
     Defaults to 0.
-T (--storesize)
     Size of the store storage above which a critical status will be generated.
     Defaults to 0 not checking.
-k (--smsrecvrate)
     Receive rate of SMSs below which a critical status will be generated.
     Defaults to 0.
-o (--smssendqwarn)
     Number of SMSs in the receive queue above which a warning status will be generated.
     Defaults to 0.
-q (--smssendqcrit)
     Number of SMSs in the receive queue above which a critical status will be generated.
     Defaults to 0.
-r (--smssendrate)
     Send rate of SMSs below which a critical status will be generated.
     Defaults to 0.
-l (--smscqueuedwarn)
     Number of SMSs queued for sending for a given connection which a warning status will be generated.
-m (--smscqueuedcrit)
     Number of SMSs queued for sending for a given connection which a critical status will be generated.
-t (--timeout)
     Timeout in seconds at which an unknown status will be generated.
     Defaults to $TIMEOUT.
-s (--secure)
     Connect to the serverly using HTTPS instead of HTTP.
     Defaults to false. (HTTP)
-H (--host)
     Hostname of the Kannel server on which the status interface is running.
     Defaults to localhost.
-P (--port)
     Port number at which the status interface is reachable on the server.
     Defaults to 13000.
-p (--password)
     Password needed to access the status interface.
     Defaults to blank (no password).
\n";

}
